version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3000:80'
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    restart: always
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - PGPORT=5432
      - PGHOST=postgres
      - PGUSER=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgress_password_change
  postgres:
    build:
      dockerfile: Dockerfile.dev
      context: ./postgres
    restart: always
    volumes:
      - ./postgres/pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
